version: '2'

services:

  # Django web server
  back:
    build:
      context: .
      dockerfile: back_dockerfile
    hostname: web
    command: ./run_web.sh
    volumes:
      - .:/app  # mount current directory inside container
    ports:
      - "8000:8000"
    # set up links so that web knows about db, rabbit and redis
    links:
      - rabbit

  # Celery worker
  front:
#    environment:
#      INVENIO_CELERY_BROKER_URL=amqp://root:lusine_admin@mq:5672//
    build:
      context: .
      dockerfile: Dockerfile
    command: ./run_celery.sh
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit